#:schema ../plugin-schema.json
name = "roadrunner"
type = "cli"

[resolve]
git-url = "https://github.com/roadrunner-server/roadrunner"

[platform.linux]
download-file = "roadrunner-{version}-linux-{arch}.tar.gz"
bin-path = "roadrunner-{version}-linux-{arch}/rr"

[platform.macos]
download-file = "roadrunner-{version}-darwin-{arch}.tar.gz"
bin-path = "roadrunner-{version}-darwin-{arch}/rr"

[platform.windows]
download-file = "roadrunner-{version}-windows-{arch}.tar.gz"
bin-path = "roadrunner-{version}-windows-{arch}/rr.exe"

[install]
download-url = "https://github.com/roadrunner-server/roadrunner/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"
