#:schema ../plugin-schema.json
name = "golangci-lint"
type = "cli"

[resolve]
git-url = "https://github.com/golangci/golangci-lint"

[platform.linux]
download-file = "golangci-lint-{version}-linux-{arch}.tar.gz"
checksum-file = "golangci-lint-{version}-checksums.txt"
bin-path = "golangci-lint-{version}-linux-{arch}/golangci-lint"

[platform.macos]
download-file = "golangci-lint-{version}-darwin-{arch}.tar.gz"
checksum-file = "golangci-lint-{version}-checksums.txt"
bin-path = "golangci-lint-{version}-darwin-{arch}/golangci-lint"

[platform.windows]
download-file = "golangci-lint-{version}-windows-{arch}.zip"
checksum-file = "golangci-lint-{version}-checksums.txt"
bin-path = "golangci-lint-{version}-windows-{arch}\\golangci-lint.exe"

[install]
download-url = "https://github.com/golangci/golangci-lint/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/golangci/golangci-lint/releases/download/v{version}/{checksum_file}"

[install.arch]
arm = "armv6"
aarch64 = "arm64"
x86 = "386"
x86_64 = "amd64"
